In [1]:
import requests
import json
import os
from dotenv import load_dotenv
import pandas as pd

load_dotenv()

def get_auth_header(token):
    print(token)
    return {"Authorization": f"Basic {token}"}

def assert_ok(http_response):
    status = http_response.status_code
    if status != 200:
        raise Exception(f"HTTP status: {status}. Body: {http_response.text}")
    return http_response.json()

def get_devops_pipeline_data(project, definition, branch, token):
    headers = get_auth_header(token)
    path = (
        f"https://dev.azure.com/{project}/_apis/build/builds?definitions={definition}&branchName={branch}&resultFilter=succeeded&statusFilter=completed&queryOrder=queueTimeDescending&api-version=6.0"
    )
    
    r = requests.get(
        path,
        headers=headers,
    )
    data = assert_ok(r)
    return data

Python-dotenv could not parse statement starting at line 3

In [2]:
BRANCH = "refs/heads/main".replace("/", "%2F")
DEFINITION_ID = 82
PROJECT = "mollerdigital/carcare" 

TOKEN = os.environ["AZURE_TOKEN"]
data = get_devops_pipeline_data(PROJECT, DEFINITION_ID, BRANCH, TOKEN)
data
df = pd.DataFrame(data["value"])

OnNoZTdwdWZ1ZmdxN3F1c2d4Mm90a2t1aHE0cTN1NmE1N3k0eTRhYXY2cWVzcXplamF3amE=

In [3]:
df = df[["id", "project", "repository", "sourceBranch",  "status", "result", "queueTime", "startTime", "finishTime", ]]
df

,id,project,repository,sourceBranch,status,result,queueTime,startTime,finishTime
0,4805,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-06-15T08:41:43.3878662Z,2022-06-15T08:41:55.423614Z,2022-06-15T09:02:47.868118Z
1,4582,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-06-08T08:57:13.9597942Z,2022-06-08T08:57:24.1327325Z,2022-06-08T09:41:00.9928567Z
2,4431,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-06-02T06:53:46.1730371Z,2022-06-02T06:54:01.2979841Z,2022-06-03T11:11:51.5678158Z
3,4419,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-06-01T08:48:16.4618811Z,2022-06-01T08:48:33.0435168Z,2022-06-01T11:51:12.8141805Z
4,4210,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-05-18T12:26:23.6332649Z,2022-05-18T12:26:33.4410769Z,2022-06-17T12:31:45.5370039Z
5,4176,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-05-16T11:57:31.8908472Z,2022-05-16T11:57:41.7548441Z,2022-06-15T12:13:46.0857277Z
6,4071,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-05-11T13:40:32.3343747Z,2022-05-11T13:40:45.3145307Z,2022-06-10T13:46:08.33159Z
7,4043,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-05-10T11:07:30.3558439Z,2022-05-10T11:07:43.2048922Z,2022-06-09T11:14:14.5453997Z

In [4]:

# df = pd.concat([df.project.apply(pd.Series), df.repository.apply(pd.Series), df.drop(['project', 'repository'], axis=1)], axis=1, keys=['project', 'repository', 'build'])
df

,id,project,repository,sourceBranch,status,result,queueTime,startTime,finishTime
0,4805,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-06-15T08:41:43.3878662Z,2022-06-15T08:41:55.423614Z,2022-06-15T09:02:47.868118Z
1,4582,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-06-08T08:57:13.9597942Z,2022-06-08T08:57:24.1327325Z,2022-06-08T09:41:00.9928567Z
2,4431,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-06-02T06:53:46.1730371Z,2022-06-02T06:54:01.2979841Z,2022-06-03T11:11:51.5678158Z
3,4419,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-06-01T08:48:16.4618811Z,2022-06-01T08:48:33.0435168Z,2022-06-01T11:51:12.8141805Z
4,4210,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-05-18T12:26:23.6332649Z,2022-05-18T12:26:33.4410769Z,2022-06-17T12:31:45.5370039Z
5,4176,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-05-16T11:57:31.8908472Z,2022-05-16T11:57:41.7548441Z,2022-06-15T12:13:46.0857277Z
6,4071,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-05-11T13:40:32.3343747Z,2022-05-11T13:40:45.3145307Z,2022-06-10T13:46:08.33159Z
7,4043,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-05-10T11:07:30.3558439Z,2022-05-10T11:07:43.2048922Z,2022-06-09T11:14:14.5453997Z

In [5]:
from datetime import datetime
from dateutil.relativedelta import relativedelta
today = datetime.today()
three_months_ago = today + relativedelta(months=-3)
dates = pd.bdate_range(three_months_ago, today)
dates = pd.DataFrame(dates, columns=['date'])
dates

         date
0  2022-03-28
1  2022-03-29
2  2022-03-30
3  2022-03-31
4  2022-04-01
..        ...
61 2022-06-21
62 2022-06-22
63 2022-06-23
64 2022-06-24
65 2022-06-27

[66 rows x 1 columns]

In [6]:
# Get holiday
year = datetime.today().year
country = os.environ["COUNTRY"]
holiday = requests.get(f"https://date.nager.at/api/v3/publicholidays/{year}/{country}")
holiday = assert_ok(holiday)
holiday = pd.DataFrame(holiday)
holiday['date'] = pd.to_datetime(holiday['date'])

In [7]:
holiday

,date,localName,name,countryCode,fixed,global,counties,launchYear,types
0,2022-01-01,Første nyttårsdag,New Year's Day,NO,True,True,None,None,[Public]
1,2022-04-14,Skjærtorsdag,Maundy Thursday,NO,False,True,None,None,[Public]
2,2022-04-15,Langfredag,Good Friday,NO,False,True,None,None,[Public]
3,2022-04-17,Første påskedag,Easter Sunday,NO,False,True,None,None,[Public]
4,2022-04-18,Andre påskedag,Easter Monday,NO,False,True,None,None,[Public]
5,2022-05-01,Første mai,Labour Day,NO,True,True,None,None,[Public]
6,2022-05-17,Syttende mai,Constitution Day,NO,True,True,None,None,[Public]
7,2022-05-26,Kristi himmelfartsdag,Ascension Day,NO,False,True,None,None,[Public]
8,2022-06-05,Første pinsedag,Pentecost,NO,False,True,None,None,[Public]
9,2022-06-06,Andre pinsedag,Whit Monday,NO,False,True,None,None,[Public]
10,2022-12-25,Første juledag,Christmas Day,NO,True,True,None,None,[Public]
11,2022-12-26,Andre juledag,St. Stephen's Day,NO,True,True,None,None,[Public]

In [8]:
dates = pd.merge(dates,holiday, indicator=True, how='left', on='date').query('_merge=="left_only"').drop('_merge', axis=1)
dates = dates['date']
dates = pd.DataFrame(dates)

In [9]:
dates

         date
0  2022-03-28
1  2022-03-29
2  2022-03-30
3  2022-03-31
4  2022-04-01
5  2022-04-04
6  2022-04-05
7  2022-04-06
8  2022-04-07
9  2022-04-08
10 2022-04-11
11 2022-04-12
12 2022-04-13
16 2022-04-19
17 2022-04-20
18 2022-04-21
19 2022-04-22
20 2022-04-25
21 2022-04-26
22 2022-04-27
23 2022-04-28
24 2022-04-29
25 2022-05-02
26 2022-05-03
27 2022-05-04
28 2022-05-05
29 2022-05-06
30 2022-05-09
31 2022-05-10
32 2022-05-11
33 2022-05-12
34 2022-05-13
35 2022-05-16
37 2022-05-18
38 2022-05-19
39 2022-05-20
40 2022-05-23
41 2022-05-24
42 2022-05-25
44 2022-05-27
45 2022-05-30
46 2022-05-31
47 2022-06-01
48 2022-06-02
49 2022-06-03
51 2022-06-07
52 2022-06-08
53 2022-06-09
54 2022-06-10
55 2022-06-13
56 2022-06-14
57 2022-06-15
58 2022-06-16
59 2022-06-17
60 2022-06-20
61 2022-06-21
62 2022-06-22
63 2022-06-23
64 2022-06-24
65 2022-06-27

In [10]:
# TODO: Merge dates object with build dates!!

df['date'] = pd.to_datetime(df['startTime']).dt.tz_localize(None).dt.normalize()
df

,id,project,repository,sourceBranch,status,result,queueTime,startTime,finishTime,date
0,4805,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-06-15T08:41:43.3878662Z,2022-06-15T08:41:55.423614Z,2022-06-15T09:02:47.868118Z,2022-06-15
1,4582,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-06-08T08:57:13.9597942Z,2022-06-08T08:57:24.1327325Z,2022-06-08T09:41:00.9928567Z,2022-06-08
2,4431,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-06-02T06:53:46.1730371Z,2022-06-02T06:54:01.2979841Z,2022-06-03T11:11:51.5678158Z,2022-06-02
3,4419,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-06-01T08:48:16.4618811Z,2022-06-01T08:48:33.0435168Z,2022-06-01T11:51:12.8141805Z,2022-06-01
4,4210,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-05-18T12:26:23.6332649Z,2022-05-18T12:26:33.4410769Z,2022-06-17T12:31:45.5370039Z,2022-05-18
5,4176,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-05-16T11:57:31.8908472Z,2022-05-16T11:57:41.7548441Z,2022-06-15T12:13:46.0857277Z,2022-05-16
6,4071,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-05-11T13:40:32.3343747Z,2022-05-11T13:40:45.3145307Z,2022-06-10T13:46:08.33159Z,2022-05-11
7,4043,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-05-10T11:07:30.3558439Z,2022-05-10T11:07:43.2048922Z,2022-06-09T11:14:14.5453997Z,2022-05-10

In [11]:
df = pd.merge(df, dates, how="outer", on="date")
df

,id,project,repository,sourceBranch,status,result,queueTime,startTime,finishTime,date
0,4805.0,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-06-15T08:41:43.3878662Z,2022-06-15T08:41:55.423614Z,2022-06-15T09:02:47.868118Z,2022-06-15
1,4582.0,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-06-08T08:57:13.9597942Z,2022-06-08T08:57:24.1327325Z,2022-06-08T09:41:00.9928567Z,2022-06-08
2,4431.0,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-06-02T06:53:46.1730371Z,2022-06-02T06:54:01.2979841Z,2022-06-03T11:11:51.5678158Z,2022-06-02
3,4419.0,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-06-01T08:48:16.4618811Z,2022-06-01T08:48:33.0435168Z,2022-06-01T11:51:12.8141805Z,2022-06-01
4,4210.0,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-05-18T12:26:23.6332649Z,2022-05-18T12:26:33.4410769Z,2022-06-17T12:31:45.5370039Z,2022-05-18
5,4176.0,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-05-16T11:57:31.8908472Z,2022-05-16T11:57:41.7548441Z,2022-06-15T12:13:46.0857277Z,2022-05-16
6,4071.0,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-05-11T13:40:32.3343747Z,2022-05-11T13:40:45.3145307Z,2022-06-10T13:46:08.33159Z,2022-05-11
7,4043.0,"{'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',...","{'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',...",refs/heads/main,completed,succeeded,2022-05-10T11:07:30.3558439Z,2022-05-10T11:07:43.2048922Z,2022-06-09T11:14:14.5453997Z,2022-05-10
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-03-28
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-03-29
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-03-30
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-03-31
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-01
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-04
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-05
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-06
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-07
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-08
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-11
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-12
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-13
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-19
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-20
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-21
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-22
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-25
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-26
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-27
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-28
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-29
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-02
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-03
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-04
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-05
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-06
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-09
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-12
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-13
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-19
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-20
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-23
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-24
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-25
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-27
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-30
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-31
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-03
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-07
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-09
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-10
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-13
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-14
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-16
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-17
54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-20
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-21
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-22
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-23
58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-24
59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-06-27

In [12]:
im_am_stupid = df.to_dict('records')
im_am_stupid

[{'id': 4805.0,
  'project': {'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',
   'name': 'carcare',
   'description': 'Customer portal',
   'url': 'https://dev.azure.com/mollerdigital/_apis/projects/d583f6a1-181e-4c08-9e5e-d3008290da82',
   'state': 'wellFormed',
   'revision': 109,
   'visibility': 'private',
   'lastUpdateTime': '2021-08-18T13:17:50.777Z'},
  'repository': {'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',
   'type': 'TfsGit',
   'name': 'workshop-booking',
   'url': 'https://dev.azure.com/mollerdigital/carcare/_git/workshop-booking',
   'clean': None,
   'checkoutSubmodules': False},
  'sourceBranch': 'refs/heads/main',
  'status': 'completed',
  'result': 'succeeded',
  'queueTime': '2022-06-15T08:41:43.3878662Z',
  'startTime': '2022-06-15T08:41:55.423614Z',
  'finishTime': '2022-06-15T09:02:47.868118Z',
  'date': Timestamp('2022-06-15 00:00:00')},
 {'id': 4582.0,
  'project': {'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',
   'name': 'carcare',
   'description': 'Customer portal',
   'url': 'https://dev.azure.com/mollerdigital/_apis/projects/d583f6a1-181e-4c08-9e5e-d3008290da82',
   'state': 'wellFormed',
   'revision': 109,
   'visibility': 'private',
   'lastUpdateTime': '2021-08-18T13:17:50.777Z'},
  'repository': {'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',
   'type': 'TfsGit',
   'name': 'workshop-booking',
   'url': 'https://dev.azure.com/mollerdigital/carcare/_git/workshop-booking',
   'clean': None,
   'checkoutSubmodules': False},
  'sourceBranch': 'refs/heads/main',
  'status': 'completed',
  'result': 'succeeded',
  'queueTime': '2022-06-08T08:57:13.9597942Z',
  'startTime': '2022-06-08T08:57:24.1327325Z',
  'finishTime': '2022-06-08T09:41:00.9928567Z',
  'date': Timestamp('2022-06-08 00:00:00')},
 {'id': 4431.0,
  'project': {'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',
   'name': 'carcare',
   'description': 'Customer portal',
   'url': 'https://dev.azure.com/mollerdigital/_apis/projects/d583f6a1-181e-4c08-9e5e-d3008290da82',
   'state': 'wellFormed',
   'revision': 109,
   'visibility': 'private',
   'lastUpdateTime': '2021-08-18T13:17:50.777Z'},
  'repository': {'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',
   'type': 'TfsGit',
   'name': 'workshop-booking',
   'url': 'https://dev.azure.com/mollerdigital/carcare/_git/workshop-booking',
   'clean': None,
   'checkoutSubmodules': False},
  'sourceBranch': 'refs/heads/main',
  'status': 'completed',
  'result': 'succeeded',
  'queueTime': '2022-06-02T06:53:46.1730371Z',
  'startTime': '2022-06-02T06:54:01.2979841Z',
  'finishTime': '2022-06-03T11:11:51.5678158Z',
  'date': Timestamp('2022-06-02 00:00:00')},
 {'id': 4419.0,
  'project': {'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',
   'name': 'carcare',
   'description': 'Customer portal',
   'url': 'https://dev.azure.com/mollerdigital/_apis/projects/d583f6a1-181e-4c08-9e5e-d3008290da82',
   'state': 'wellFormed',
   'revision': 109,
   'visibility': 'private',
   'lastUpdateTime': '2021-08-18T13:17:50.777Z'},
  'repository': {'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',
   'type': 'TfsGit',
   'name': 'workshop-booking',
   'url': 'https://dev.azure.com/mollerdigital/carcare/_git/workshop-booking',
   'clean': None,
   'checkoutSubmodules': False},
  'sourceBranch': 'refs/heads/main',
  'status': 'completed',
  'result': 'succeeded',
  'queueTime': '2022-06-01T08:48:16.4618811Z',
  'startTime': '2022-06-01T08:48:33.0435168Z',
  'finishTime': '2022-06-01T11:51:12.8141805Z',
  'date': Timestamp('2022-06-01 00:00:00')},
 {'id': 4210.0,
  'project': {'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',
   'name': 'carcare',
   'description': 'Customer portal',
   'url': 'https://dev.azure.com/mollerdigital/_apis/projects/d583f6a1-181e-4c08-9e5e-d3008290da82',
   'state': 'wellFormed',
   'revision': 109,
   'visibility': 'private',
   'lastUpdateTime': '2021-08-18T13:17:50.777Z'},
  'repository': {'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',
   'type': 'TfsGit',
   'name': 'workshop-booking',
   'url': 'https://dev.azure.com/mollerdigital/carcare/_git/workshop-booking',
   'clean': None,
   'checkoutSubmodules': False},
  'sourceBranch': 'refs/heads/main',
  'status': 'completed',
  'result': 'succeeded',
  'queueTime': '2022-05-18T12:26:23.6332649Z',
  'startTime': '2022-05-18T12:26:33.4410769Z',
  'finishTime': '2022-06-17T12:31:45.5370039Z',
  'date': Timestamp('2022-05-18 00:00:00')},
 {'id': 4176.0,
  'project': {'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',
   'name': 'carcare',
   'description': 'Customer portal',
   'url': 'https://dev.azure.com/mollerdigital/_apis/projects/d583f6a1-181e-4c08-9e5e-d3008290da82',
   'state': 'wellFormed',
   'revision': 109,
   'visibility': 'private',
   'lastUpdateTime': '2021-08-18T13:17:50.777Z'},
  'repository': {'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',
   'type': 'TfsGit',
   'name': 'workshop-booking',
   'url': 'https://dev.azure.com/mollerdigital/carcare/_git/workshop-booking',
   'clean': None,
   'checkoutSubmodules': False},
  'sourceBranch': 'refs/heads/main',
  'status': 'completed',
  'result': 'succeeded',
  'queueTime': '2022-05-16T11:57:31.8908472Z',
  'startTime': '2022-05-16T11:57:41.7548441Z',
  'finishTime': '2022-06-15T12:13:46.0857277Z',
  'date': Timestamp('2022-05-16 00:00:00')},
 {'id': 4071.0,
  'project': {'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',
   'name': 'carcare',
   'description': 'Customer portal',
   'url': 'https://dev.azure.com/mollerdigital/_apis/projects/d583f6a1-181e-4c08-9e5e-d3008290da82',
   'state': 'wellFormed',
   'revision': 109,
   'visibility': 'private',
   'lastUpdateTime': '2021-08-18T13:17:50.777Z'},
  'repository': {'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',
   'type': 'TfsGit',
   'name': 'workshop-booking',
   'url': 'https://dev.azure.com/mollerdigital/carcare/_git/workshop-booking',
   'clean': None,
   'checkoutSubmodules': False},
  'sourceBranch': 'refs/heads/main',
  'status': 'completed',
  'result': 'succeeded',
  'queueTime': '2022-05-11T13:40:32.3343747Z',
  'startTime': '2022-05-11T13:40:45.3145307Z',
  'finishTime': '2022-06-10T13:46:08.33159Z',
  'date': Timestamp('2022-05-11 00:00:00')},
 {'id': 4043.0,
  'project': {'id': 'd583f6a1-181e-4c08-9e5e-d3008290da82',
   'name': 'carcare',
   'description': 'Customer portal',
   'url': 'https://dev.azure.com/mollerdigital/_apis/projects/d583f6a1-181e-4c08-9e5e-d3008290da82',
   'state': 'wellFormed',
   'revision': 109,
   'visibility': 'private',
   'lastUpdateTime': '2021-08-18T13:17:50.777Z'},
  'repository': {'id': '2b19f00a-64ef-4a1d-867a-bd487830ac1d',
   'type': 'TfsGit',
   'name': 'workshop-booking',
   'url': 'https://dev.azure.com/mollerdigital/carcare/_git/workshop-booking',
   'clean': None,
   'checkoutSubmodules': False},
  'sourceBranch': 'refs/heads/main',
  'status': 'completed',
  'result': 'succeeded',
  'queueTime': '2022-05-10T11:07:30.3558439Z',
  'startTime': '2022-05-10T11:07:43.2048922Z',
  'finishTime': '2022-06-09T11:14:14.5453997Z',
  'date': Timestamp('2022-05-10 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-03-28 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-03-29 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-03-30 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-03-31 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-04-01 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-04-04 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-04-05 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-04-06 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-04-07 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-04-08 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-04-11 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-04-12 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-04-13 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-04-19 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-04-20 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-04-21 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-04-22 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-04-25 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-04-26 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-04-27 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-04-28 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-04-29 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-05-02 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-05-03 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-05-04 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-05-05 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-05-06 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-05-09 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-05-12 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-05-13 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-05-19 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-05-20 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-05-23 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-05-24 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-05-25 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-05-27 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-05-30 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-05-31 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-06-03 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-06-07 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-06-09 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-06-10 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-06-13 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-06-14 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-06-16 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-06-17 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-06-20 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-06-21 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-06-22 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-06-23 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-06-24 00:00:00')},
 {'id': nan,
  'project': nan,
  'repository': nan,
  'sourceBranch': nan,
  'status': nan,
  'result': nan,
  'queueTime': nan,
  'startTime': nan,
  'finishTime': nan,
  'date': Timestamp('2022-06-27 00:00:00')}]

In [13]:
release_per_day = []
import math
for item in im_am_stupid:
    try:
        index = release_per_day.index(next(filter(lambda x: x.get('date') == item.get('date'), release_per_day)))
        release_per_day[index]['count'] +=  1
    except:
        release_per_day.append({'date': item.get('date'), 'count': int(not math.isnan(item.get('id')))})
release_per_day = sorted(release_per_day, key=lambda d: d['date']) 
release_per_day = pd.DataFrame(release_per_day)
release_per_day

         date  count
0  2022-03-28      0
1  2022-03-29      0
2  2022-03-30      0
3  2022-03-31      0
4  2022-04-01      0
5  2022-04-04      0
6  2022-04-05      0
7  2022-04-06      0
8  2022-04-07      0
9  2022-04-08      0
10 2022-04-11      0
11 2022-04-12      0
12 2022-04-13      0
13 2022-04-19      0
14 2022-04-20      0
15 2022-04-21      0
16 2022-04-22      0
17 2022-04-25      0
18 2022-04-26      0
19 2022-04-27      0
20 2022-04-28      0
21 2022-04-29      0
22 2022-05-02      0
23 2022-05-03      0
24 2022-05-04      0
25 2022-05-05      0
26 2022-05-06      0
27 2022-05-09      0
28 2022-05-10      1
29 2022-05-11      1
30 2022-05-12      0
31 2022-05-13      0
32 2022-05-16      1
33 2022-05-18      1
34 2022-05-19      0
35 2022-05-20      0
36 2022-05-23      0
37 2022-05-24      0
38 2022-05-25      0
39 2022-05-27      0
40 2022-05-30      0
41 2022-05-31      0
42 2022-06-01      1
43 2022-06-02      1
44 2022-06-03      0
45 2022-06-07      0
46 2022-06-08      1
47 2022-06-09      0
48 2022-06-10      0
49 2022-06-13      0
50 2022-06-14      0
51 2022-06-15      1
52 2022-06-16      0
53 2022-06-17      0
54 2022-06-20      0
55 2022-06-21      0
56 2022-06-22      0
57 2022-06-23      0
58 2022-06-24      0
59 2022-06-27      0

In [14]:
release_per_day['week_start_date'] =  pd.to_datetime(release_per_day['date']) - pd.to_timedelta(7, unit='d')
release_per_day = release_per_day.groupby(['date', pd.Grouper(key='week_start_date', freq='W-MON')]).sum().reset_index()

In [20]:
release_days_per_week = release_per_day.groupby('week_start_date').sum().reset_index()
release_days_per_week

   week_start_date  count
0       2022-03-21      0
1       2022-03-28      0
2       2022-04-04      0
3       2022-04-11      0
4       2022-04-18      0
5       2022-04-25      0
6       2022-05-02      0
7       2022-05-09      3
8       2022-05-16      1
9       2022-05-23      0
10      2022-05-30      2
11      2022-06-06      1
12      2022-06-13      1
13      2022-06-20      0

In [16]:
median_days_per_week = release_days_per_week['count'].median()

In [21]:
releases_per_month = release_days_per_week.groupby(pd.Grouper(key='week_start_date', freq='MS')).sum().reset_index()
releases_per_month = releases_per_month.rename(columns={"week_start_date": "month_start_date"})
releases_per_month

  month_start_date  count
0       2022-03-01      0
1       2022-04-01      0
2       2022-05-01      6
3       2022-06-01      2

In [18]:
median_days_per_month = releases_per_month['count'].median()
median_days_per_month

1.0

In [19]:
# Find median of deployment days in week.
# If more or equals then 3 then daily
# If atleast ones each week then weekly
# If atleast ones each month then monthly
# Else yearly

def deployment_frequency(frequency_week, frequency_month):
    if (frequency_week >= 3):
        return 'Daily'
    elif (frequency_week >= 1):
        return 'Weekly'
    elif (frequency_month >= 1):
        return 'Monthly'
    else:
        return 'Yearly'
deployment_frequency(median_days_per_week, median_days_per_month)

'Monthly'